### ISSUE TITLE
Integrate with defx

### ISSUE THREAD

**Issue by petobens** [kmnk/denite-dirmark#2]
Is it possible to integrate this source with defx file manager? Thanks!

**Comment by Shougo** [comment]
I think the source can add the action like `defx/history` source.

**Comment by kmnk** [comment]
Thanks for your suggestion @petobens , and tfor your help @Shougo .

I use dirmark and defx too.
So, I try implement it on next update.

thanks

**Comment by kmnk** [comment]
Sorry, I don't aware pull request.

https://github.com/kmnk/denite-dirmark/pull/3

I read it later. thanks

**Comment by petobens** [comment]
> I read it later. thanks

Thank you!
