### ISSUE TITLE
Cannot input group and mark name

### ISSUE THREAD

**Issue by kmnk** [kmnk/denite-dirmark#6]
Now, fix commit pushed ( 600958cd461c2a73e69a9bf5d3178bcbf2b86616 ) for using new denite prompt interface `denite#util#input` .

But not be displayed input prompt.

Should fix it...

**Comment by Shougo** [comment]
It is denite bug.
Please wait.  I will fix it later.

**Comment by Shougo** [comment]
It is already fixed.

**Comment by kmnk** [comment]
Thanks ! :)
