### ISSUE TITLE
`cache_directory_path` is misleading

### ISSUE THREAD

**Issue by roosemberth** [kmnk/denite-dirmark#7]
Hi,

First of all, thanks for the plugin!

The plugin stores the list of bookmarks in the file inside `cache_directory_path`, this is very misleading since caches are expected to be deleted at any point (e.g. if the system is running low on disk space), but deleting this file would cause the user to lose their bookmarks, which is annoying.

I suggest the option to be renamed to `data_directory_path`, maybe keep the previous setters with warnings that their use shall be deprecated.

**Comment by kmnk** [comment]
True, I think so too.

I'll try to add new variable and obsolete current variable on next version.

Thanks !

**Comment by kmnk** [comment]
Renamed by https://github.com/kmnk/denite-dirmark/commit/8000860b6ce77920eb049a5a7563fe87ca29a0d0 and https://github.com/kmnk/denite-dirmark/commit/e152abb6ef1f564b3f313e4bda703ea90da26260 .

Thanks
